server:
  port: 8090
spring:
  application:
    name: USERS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/booksService?createDatabaseIfNotExist=true
    username: root
    password:

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

    hibernate:
      ddl-auto: create


